### ISSUE TITLE
Index Subsystem

### ISSUE THREAD

**Issue by SixtyFiveOhTwo** [Robotiators-888/2022Season#16]
Create one Index subsystem class to represent the Index on the bot. the top spot below the shooter is one and the position for balls to be stored below that is 2.

Methods
- getPosition this method should return a boolean and take in an int the integer should indicate which position this method is checking for a ball in and then, this should return true is there is one and false otherwise.
- getColor this method should take in an int and operate the same as getPosition except instead of returning a boolean it returns the 
current color of the ball in the location .
- feed this method should feed the ball from position one into the shooter
- setSpeedFront, setSpeedBack , and setSpeedTower these methods are all exactly the same they should return nothing and take in a double to set the corresponding motor controller's speed to

**Comment by KevinH45** [comment]
I finished the subsystem with all required functions in the Index branch.

**Comment by SixtyFiveOhTwo** [comment]
you should have made a pull request into main with your index subsystem before you close the issue, please go ahead and make one .

**Comment by KevinH45** [comment]
I haven't tested if Index works, it just builds. Should I submit a pull request to main or should I make a pull request to Integration?

**Comment by liam-a-wms** [comment]
First is to test if it actually works. Untested code should never be merged anywhere.

**Comment by KevinH45** [comment]
I created a pull request and made sure it builded

**Comment by liam-a-wms** [comment]
The issue should remain open until the associated pull request is merged.
