### ISSUE TITLE
Intake subsystem

### ISSUE THREAD

**Issue by SixtyFiveOhTwo** [Robotiators-888/2022Season#8]
Create one intake subsystem class to represent both intakes on the bot. the constructor should take in the CAN ID of the motor controller and the port numbers on the PCM as parameters.

Methods
- intakeSet takes in boolean True if extended False is retracted
- intakeGet returns boolean True if extended False is retracted
- intakeSpeedSet takes in a double which represents percentage speed to set the intake motor to
- intakeSpeedGet returns double which represents percentage speed to set the intake motor to

**Comment by Gliu1211** [comment]
Completed
